/* RIGOR — measure the styles, don't describe them.
   docs/STYLES_MEASURED.md has claimed since round 7 to be "generated by
   tests/rigor_styles.js". It was not: no such file existed, and the numbers
   in it were produced once by hand and then edited by successive rounds.
   That is how the document came to assert the OPPOSITE of what the code
   did for five rounds running.

   This is that file. Run it and paste, or diff it against the doc.
     node tests/rigor_styles.js
     node tests/rigor_styles.js --md     (markdown tables only)
*/
'use strict';
var R = require('../rigor_core.js');

var FS = 48000;

function styled(name, patch) {
  var s = R.defaultState(), d = R.styleDefaults(name);
  for (var k in d) s[k] = d[k];
  s.style = name;
  if (patch) for (var k2 in patch) s[k2] = patch[k2];
  return s;
}

/* All styles driven IDENTICALLY. Every knob is stated explicitly so the
   only difference between the rows is the topology — which is the entire
   point of the measurement. */
var COMMON = { thresh: -30, ratio: 4, knee: 0, attack: 20, release: 400,
               autoRel: false, makeup: 0, autoMakeup: false, hold: 0,
               holdTaper: 0, curve: 0, mix: 100, link: 100, range: 60 };

function stepResponse(name) {
  var n = Math.round(FS * 0.5);
  var amp = Math.pow(10, -10 / 20);          /* a -10 dBFS step */
  var sig = new Float64Array(n);
  for (var i = 0; i < n; i++) sig[i] = amp;   /* DC step: the level IS the level */
  var e = R.createEngine(FS);
  e.setState(styled(name, COMMON));
  var a = new Float64Array(n), b = new Float64Array(n);
  e.process(sig, sig, a, b);
  /* gain reduction in dB, sample by sample, derived from what came out */
  var gr = new Float64Array(n);
  for (i = 0; i < n; i++) gr[i] = 20 * Math.log10(Math.abs(a[i]) / amp);
  var settled = gr[n - 1];
  /* time to 63.2% of the SETTLED reduction — the definition is stated so
     the number means something; it will not match Pro-C's and need not */
  var target = settled * 0.632, tSamp = -1;
  for (i = 0; i < n; i++) if (gr[i] <= target) { tSamp = i; break; }
  return { settled: settled, ms: tSamp < 0 ? NaN : tSamp / FS * 1000 };
}

/* the PATH signature, read out of the table rather than asserted by hand */
function pathOf(s) {
  var c = R.STYLE[s];
  return { topo: c.topo === 'fb' ? 'feedback' : 'feedforward',
           detect: c.detect === 'rms' ? 'RMS ' + c.rmsMs + ' ms' : 'peak',
           env: c.smoothLevel ? 'level' : 'gain',
           pk: c.pkMs + ' ms',
           lvlAtt: c.levelAttack ? 'yes' : '—',
           sig: c.topo + '|' + c.detect + '|' + c.rmsMs + '|' + c.pkMs + '|' +
                c.smoothLevel + '|' + c.levelAttack };
}

/* do two styles RENDER identically? The only question that settles it. */
function rendersSame(a, b) {
  var n = 4096, src = R.makeNoise(9001, n);
  for (var i = 0; i < n; i++) src[i] *= 0.7;
  function go(name) {
    var e = R.createEngine(FS);
    e.setState(styled(name, COMMON));
    var oa = new Float64Array(n), ob = new Float64Array(n);
    e.process(src, src, oa, ob);
    return oa;
  }
  var x = go(a), y = go(b);
  for (i = 0; i < n; i++) if (x[i] !== y[i]) return false;
  return true;
}

var md = process.argv.indexOf('--md') !== -1;
var lines = [];
function out(s) { lines.push(s); }

out('| Style | Topology | Detector | Envelope on | Peak decay | Level-dep. attack | Settled GR | Time to 63.2% |');
out('|---|---|---|---|---|---|---|---|');
R.STYLES.forEach(function (s) {
  var p = pathOf(s), r = stepResponse(s);
  out('| **' + s + '** | ' + p.topo + ' | ' + p.detect + ' | ' + p.env + ' | ' + p.pk +
      ' | ' + p.lvlAtt + ' | ' + r.settled.toFixed(2) + ' dB | ' + r.ms.toFixed(1) + ' ms |');
});

/* distinct paths, grouped */
var groups = {};
R.STYLES.forEach(function (s) {
  var k = pathOf(s).sig;
  (groups[k] = groups[k] || []).push(s);
});
var keys = Object.keys(groups);
out('');
out('**' + keys.length + ' distinct signal paths across ' + R.STYLES.length + ' styles.**');
out('');
out('| Path | Styles |');
out('|---|---|');
keys.forEach(function (k) {
  var g = groups[k], one = pathOf(g[0]);
  out('| ' + one.topo + ' · ' + one.detect + ' · ' + one.env + '-smoothed · peak decay ' +
      one.pk + (one.lvlAtt === 'yes' ? ' · level-dependent attack' : '') +
      ' | ' + g.map(function (x) { return '**' + x + '**'; }).join(', ') + ' |');
});

/* the render check, for every pair */
out('');
out('| Pair | Same path? | Renders identically? |');
out('|---|---|---|');
for (var i = 0; i < R.STYLES.length; i++) {
  for (var j = i + 1; j < R.STYLES.length; j++) {
    var a = R.STYLES[i], b = R.STYLES[j];
    var samePath = pathOf(a).sig === pathOf(b).sig;
    var sameRender = rendersSame(a, b);
    out('| ' + a + ' / ' + b + ' | ' + (samePath ? 'yes' : 'no') + ' | ' +
        (sameRender ? 'yes' : 'no') + (samePath === sameRender ? '' : '  **MISMATCH**') + ' |');
  }
}

out('');
out('| Style | Ratio | Knee | Attack | Release | Auto-release |');
out('|---|---|---|---|---|---|');
R.STYLES.forEach(function (s) {
  var d = R.styleDefaults(s);
  out('| ' + s + ' | ' + d.ratio + ':1 | ' + d.knee + ' dB | ' + d.attack + ' ms | ' +
      d.release + ' ms | ' + (d.autoRel ? 'on' : 'off') + ' |');
});

if (!md) {
  console.log('RIGOR — the styles, measured at ' + FS + ' Hz');
  console.log('All driven identically: threshold ' + COMMON.thresh + ', ' + COMMON.ratio +
              ':1, hard knee, ' + COMMON.attack + ' ms attack, ' + COMMON.release +
              ' ms release, auto-release off, on a -10 dBFS step.');
  console.log('');
}
console.log(lines.join('\n'));
