/* CASKET parity emitter — writes tests/parity_expected.h from the JS core.
   node tests/parity_emit.js
   The JS is the source of truth; the C++ twin must match it BIT-EXACTLY.
   Values are emitted with toExponential(17) so the C++ literals round-trip
   to the identical double. CI regenerates this file and fails on any diff,
   so a JS change that moves the bits cannot land silently. */
'use strict';
var fs = require('fs');
var path = require('path');
var C = require('../casket_core.js');

var FS = 48000;
var out = [];
function head(s) { out.push('/* ' + s + ' */'); }
function lit(v) {
  if (!isFinite(v)) return v > 0 ? 'INFINITY' : '-INFINITY';
  return v.toExponential(17);
}
function arr(name, vals) {
  out.push('static const double ' + name + '[' + vals.length + '] = {');
  for (var i = 0; i < vals.length; i += 4) {
    out.push('  ' + vals.slice(i, i + 4).map(lit).join(', ') + (i + 4 < vals.length ? ',' : ''));
  }
  out.push('};');
}
function count(name, v) { out.push('static const int ' + name + ' = ' + v + ';'); }

out.push('/* GENERATED by tests/parity_emit.js — do not edit by hand. */');
out.push('#pragma once');
out.push('#include <cmath>');
out.push('');

/* ---- 1. oversampler taps, every lining ---- */
head('oversampler: full tap vector for each lining, then each phase sum');
var tapVals = [], tapOff = [0], phaseSums = [];
C.LININGS.forEach(function (M) {
  var o = C.designOversampler(M, C.OS_Q);
  for (var k = 0; k < o.len; k++) tapVals.push(o.taps[k]);
  tapOff.push(tapVals.length);
  for (var p = 0; p < o.phases.length; p++) {
    var s = 0;
    for (var j = 0; j < o.phases[p].length; j++) s += o.phases[p][j];
    phaseSums.push(s);
  }
});
arr('EXP_TAPS', tapVals);
out.push('static const int EXP_TAP_OFF[' + tapOff.length + '] = { ' + tapOff.join(', ') + ' };');
arr('EXP_PHASE_SUMS', phaseSums);
count('EXP_PHASE_SUM_N', phaseSums.length);

/* ---- 1b. the seal's decimator, every legal sealed lining ---- */
head('decimator: full tap vector for each sealed lining (1x is illegal sealed)');
var decVals = [], decOff = [0];
[2, 4, 8, 16].forEach(function (M) {
  var d = C.designDecimator(M, C.DEC_Q, C.DEC_CUT);
  for (var k = 0; k < d.len; k++) decVals.push(d.taps[k]);
  decOff.push(decVals.length);
});
arr('EXP_DEC', decVals);
out.push('static const int EXP_DEC_OFF[' + decOff.length + '] = { ' + decOff.join(', ') + ' };');

/* ---- 2. K-weighting at several rates ---- */
head('K-weighting coefficients at 44100 / 48000 / 88200 / 96000');
var RATES = [44100, 48000, 88200, 96000];
var kw = [];
RATES.forEach(function (r) {
  var k = C.kWeight(r);
  kw.push(k.shelf.b0, k.shelf.b1, k.shelf.b2, k.shelf.a1, k.shelf.a2);
  kw.push(k.hp.b0, k.hp.b1, k.hp.b2, k.hp.a1, k.hp.a2);
});
arr('EXP_KW', kw);
out.push('static const double EXP_RATES[' + RATES.length + '] = { ' +
         RATES.map(function (r) { return r + '.0'; }).join(', ') + ' };');
count('EXP_RATE_N', RATES.length);

/* ---- 3. gain computer across the knee ---- */
head('gain computer: 201 points from -40 to +10 dB, at three knee widths');
var gc = [];
[0, 3, 12].forEach(function (W) {
  for (var i = 0; i <= 200; i++) {
    var x = -40 + i * 0.25;
    gc.push(C._nd.kneeGain(x, -1.0, W, 0));
  }
});
arr('EXP_GC', gc);
count('EXP_GC_N', gc.length);

/* ---- 4. transferAt for each arrangement ---- */
head('transferAt: 41 points from -40 to 0 dB, per arrangement');
var tf = [];
C.STYLES.forEach(function (name) {
  var s = C.defaultState(), d = C.styleDefaults(name);
  for (var k in d) s[k] = d[k];
  s.style = name; s.drive = 6; s.lid = -1.0;
  for (var i = 0; i <= 40; i++) tf.push(C.transferAt(s, -40 + i));
});
arr('EXP_TF', tf);
count('EXP_TF_N', tf.length);

/* ---- 5. rendered audio, every arrangement plus the awkward cases ---- */
head('rendered audio: stride-13 samples of a 6000-sample clipped-noise render');
var N = 6000, STRIDE = 13;
function source(seed, scale) {
  var a = C.makeNoise(seed, N);
  for (var i = 0; i < N; i++) {
    var v = a[i] * scale;
    a[i] = v > 1 ? 1 : (v < -1 ? -1 : v);
  }
  return a;
}
var CASES = [];
C.STYLES.forEach(function (name) {
  CASES.push({ name: name, patch: {}, style: name });
});
CASES.push({ name: 'lining16', style: 'velvet', patch: { lining: 16, vigil: 4, knee: 6, hold: 20 } });
CASES.push({ name: 'lining1', style: 'pine', patch: { lining: 1, vigil: 0.5 } });
CASES.push({ name: 'linked0', style: 'velvet', patch: { link: 0, drive: 14 } });
CASES.push({ name: 'dusted', style: 'pine', patch: { dust: 'shaped', dustBits: 16, dustSeed: 4711 } });
CASES.push({ name: 'saturated', style: 'iron', patch: { sat: 90, drive: 15, unity: true } });
CASES.push({ name: 'sealed2x', style: 'velvet', patch: { seal: true, lining: 2, drive: 12 } });
CASES.push({ name: 'sealed4x', style: 'velvet', patch: { seal: true, lining: 4, drive: 12 } });
CASES.push({ name: 'sealed16x', style: 'velvet', patch: { seal: true, lining: 16, vigil: 1 } });
CASES.push({ name: 'sealedDust', style: 'lead', patch: { dust: 'shaped', dustBits: 24, dustSeed: 909 } });
CASES.push({ name: 'midside', style: 'velvet', patch: { ms: true, msMid: 3, msSide: -4, drive: 10 } });
CASES.push({ name: 'split', style: 'velvet', patch: { drive: 12 }, split: true });
/* BYPASS. Added the day bypass stopped being a wire and became a
   latency-compensated delay. Until then the only bypassed audio in this
   gate was a metering case, and the twin could have got the delay wrong
   in a way that only showed up as a fourth decimal place of LRA. Now the
   C++ has to reproduce the delayed samples themselves. */
CASES.push({ name: 'bypassed', style: 'velvet', patch: { bypass: true, drive: 9 } });
CASES.push({ name: 'bypassSealed', style: 'lead', patch: { bypass: true, seal: true } });

var rend = [], rendOff = [0], names = [];
CASES.forEach(function (c) {
  var s = C.defaultState(), d = C.styleDefaults(c.style);
  for (var k in d) s[k] = d[k];
  s.style = c.style; s.lid = -1.0; s.drive = 9;
  for (var k2 in c.patch) s[k2] = c.patch[k2];
  var e = C.createEngine(FS);
  e.setState(s);
  var inL = source(424242, 4), inR = source(133742, 4);
  var oL = new Float64Array(N), oR = new Float64Array(N);
  if (c.split) {
    /* render in awkward, non-multiple-of-CTRL chunks so the parity gate
       also proves the control-phase carry is mirrored in C++ */
    var chunks = [111, 333, 7, 1024, 240], ci = 0, p = 0;
    while (p < N) {
      var m = Math.min(chunks[ci % chunks.length], N - p);
      e.process(inL.subarray(p, p + m), inR.subarray(p, p + m),
                oL.subarray(p, p + m), oR.subarray(p, p + m));
      p += m; ci++;
    }
  } else {
    e.process(inL, inR, oL, oR);
  }
  for (var i = 0; i < N; i += STRIDE) { rend.push(oL[i]); rend.push(oR[i]); }
  /* the meters are part of the contract too */
  var m = e.meters();
  rend.push(m.peak, m.truePeak, m.gr, m.grPeak);
  /* THE TRACE, which is display-only and therefore exactly the kind of
     surface that drifts between the two languages without anybody
     noticing — the plugin editor draws from it and no audio depends on
     it, so nothing else would ever catch a divergence. */
  var tr = e.trace();
  rend.push(tr.inPeak, tr.outPeak, tr.gr, tr.inPeakDb, tr.outPeakDb);
  rendOff.push(rend.length);
  names.push(c.name);
});
arr('EXP_REND', rend);
out.push('static const int EXP_REND_OFF[' + rendOff.length + '] = { ' + rendOff.join(', ') + ' };');
out.push('static const char* const EXP_REND_NAMES[' + names.length + '] = { ' +
         names.map(function (n) { return '"' + n + '"'; }).join(', ') + ' };');
count('EXP_REND_N', names.length);
count('EXP_REND_LEN', N);
count('EXP_REND_STRIDE', STRIDE);

/* ---- 5b. loudness range ---- */
head('LRA: EBU Tech 3342 on a two-level programme');
var lraVals = [];
[[[-20, 8], [-30, 8], [-20, 8], [-30, 8]], [[-20, 8], [-26, 8], [-20, 8], [-26, 8]]].forEach(function (prog) {
  var s2 = C.defaultState(); s2.bypass = true;
  var e2 = C.createEngine(FS);
  e2.setState(s2);
  prog.forEach(function (seg) {
    var x = C.makeSine(1000, FS, Math.round(FS * seg[1]), Math.pow(10, seg[0] / 20));
    var a = new Float64Array(x.length), b = new Float64Array(x.length);
    e2.process(x, x, a, b);
  });
  var m2 = e2.meters();
  lraVals.push(m2.lra, m2.integrated);
  /* THE PICTURE, NOT ONLY THE FIGURE — added 2026-08-19.
     Both faces now draw THE RANGE, and until this existed nothing said the
     two drew the SAME distribution. The LRA number was gated; the bins it
     is computed from were not, so the JS and C++ charts could in principle
     have disagreed about the shape while agreeing about the spread.
     This reverses the "diagnostic, therefore ungated" stance recorded on
     2026-08-18 — and reverses it on a real change of circumstance rather
     than a change of mind. That stance was correct while histogramS fed one
     canvas; the moment a second face draws from it, "the two pictures
     match" becomes a guarantee worth having, and a guarantee worth having
     is exactly what earns parity surface.
     Sparse on purpose: emitting all 751 bins per programme would add ~1,500
     mostly-zero checks. The populated bins, the gate and the percentiles
     are the whole content of the picture. */
  var h2 = e2.histogramS();
  lraVals.push(h2.bins.length, h2.gate, h2.p10 === null ? -999 : h2.p10,
               h2.p95 === null ? -999 : h2.p95, h2.lra);
  h2.bins.forEach(function (b) { lraVals.push(b.loudness, b.count); });
});
arr('EXP_LRA', lraVals);
count('EXP_LRA_N', lraVals.length);

/* ---- 6. latency table ---- */
head('latency: every lining x a few vigils');
var latv = [];
C.LININGS.forEach(function (M) {
  [0.1, 1, 2, 5, 20].forEach(function (v) {
    [false, true].forEach(function (seal) {
      var s = C.defaultState();
      s.lining = M; s.vigil = v; s.seal = seal;
      latv.push(C.latencySamples(s, FS));
    });
  });
});
out.push('static const int EXP_LAT[' + latv.length + '] = { ' + latv.join(', ') + ' };');
count('EXP_LAT_N', latv.length);

/* ---- 7. THE OFFLINE TOOLS ----
   Ported to C++ this round after living only in JS for four rounds. A port
   that is merely "equivalent" is a port that drifts, so every scalar these
   tools return is gated bit-exactly — including the ones a person would
   call cosmetic, because `reached` and `covered` are the fields users act
   on and a boolean that disagrees between the twins is a plugin that
   contradicts the browser. */
head('offline tools: renderOffline, autoDrive, autoMargin, difference');
var offVals = [], offN = 0;
(function () {
  /* 24000 samples = 0.5 s. NOT arbitrary: BS.1770 integrates 400 ms
     blocks, so anything shorter never opens the gate and `integrated` is
     -Infinity at EVERY drive. The first version of this section used 4096
     samples (85 ms) and every autoDrive check passed VACUOUSLY — the tool
     took its "nothing measurable" early-out six times out of six, and a
     mutation test proved it: deleting the rail probes from the C++ twin
     changed not one of 22,848 checks. A gate that cannot fail is not a
     gate. 0.5 s clears the block with room to spare. */
  var N = 24000;
  /* three materials with genuinely different residual behaviour, so a
     mistake in the bisection or the reconstruction shows up somewhere */
  var mats = [
    ['noise', C.makeNoise(31, N), C.makeNoise(32, N)],
    ['sine',  C.makeSine(997, FS, N, 0.85), C.makeSine(1103, FS, N, 0.85)],
    ['clipped', (function () {
        var a = C.makeNoise(33, N);
        for (var i = 0; i < N; i++) { var v = a[i] * 3; a[i] = v > 1 ? 1 : (v < -1 ? -1 : v); }
        return a;
      })(), C.makeNoise(34, N)]
  ];
  var styles = ['pine', 'lead'];
  mats.forEach(function (m) {
    styles.forEach(function (sty) {
      var st = C.defaultState();
      var d = C.styleDefaults(sty);
      for (var k in d) if (Object.prototype.hasOwnProperty.call(d, k)) st[k] = d[k];
      st.style = sty; st.drive = 4; st.dust = 'off';

      /* renderOffline: the meters, plus samples from across the buffer so a
         divergence that only appears late still gets caught */
      var r = C.renderOffline(st, m[1], m[2], FS);
      offVals.push(r.meters.integrated, r.meters.momentary, r.meters.shortTerm,
                   r.meters.lra, r.meters.peakDb, r.meters.truePeakDb,
                   r.meters.grPeak, r.latency);
      [0, 1, 37, 512, 2048, 23999].forEach(function (i) {
        offVals.push(r.L[i], r.R[i]);
      });

      /* autoDrive: few passes so the emitter stays quick, but the rails are
         probed either way and that is the part most likely to diverge */
      var ad = C.autoDrive(st, m[1], m[2], FS, -14, 4);
      offVals.push(ad.drive, ad.lufs, ad.truePeak, ad.gr, ad.error,
                   ad.reached ? 1 : 0, ad.grid);

      /* UNREACHABLE TARGETS, so the RAIL is the winning answer.
         Without these the gate is blind to the rail probes entirely:
         removing `consider(lo,...)` and `consider(hi,...)` from the C++
         twin changed not one of 22,800 checks, because with a reachable
         target no rail is ever closest and the code path is dead in the
         test data. That is the powers-of-two lesson wearing new clothes —
         test data that happens to avoid the branch is test data that
         cannot defend it. -40 forces the floor, +6 forces the ceiling. */
      [-40, 6].forEach(function (tgt) {
        var ar = C.autoDrive(st, m[1], m[2], FS, tgt, 4);
        offVals.push(ar.drive, ar.lufs, ar.error, ar.reached ? 1 : 0);
      });

      /* autoMargin: the independent 16x reconstruction lives in here, so
         this is also the gate on truePeakOf */
      var am = C.autoMargin(st, m[1], m[2], FS, 3);
      offVals.push(am.truePeak, am.verifiedPeak, am.lid, am.residual,
                   am.margin, am.covered ? 1 : 0);
    });

    /* difference between the two styles on the same material */
    function styled(sty) {
      var st = C.defaultState();
      var d = C.styleDefaults(sty);
      for (var k in d) if (Object.prototype.hasOwnProperty.call(d, k)) st[k] = d[k];
      st.style = sty; st.drive = 4; st.dust = 'off';
      return st;
    }
    var df = C.difference(styled('pine'), styled('lead'), m[1], m[2], FS);
    offVals.push(df.peakDb, df.rmsDb, df.identical ? 1 : 0, df.latencyA, df.latencyB);
    [0, 100, 1000, 23999].forEach(function (i) { offVals.push(df.L[i], df.R[i]); });
  });
  offN = offVals.length;
})();
/* the quantiser, over the values where the two spellings diverge */
head('quantize: exact halves and negative halves, where round() forms disagree');
var qv = [];
[[0.35,0.1],[-0.35,0.1],[-9.75,0.1],[0.25,0.1],[-0.05,0.1],[2.5,1],[-2.5,1],
 [0.15,0.1],[-0.15,0.1],[13.45,0.1],[-11.95,0.1],[0.005,0.01],[-0.005,0.01]]
  .forEach(function (a) { qv.push(C.quantize(a[0], a[1])); });
arr('EXP_QUANT', qv);
count('EXP_QUANT_N', qv.length);

arr('EXP_OFFLINE', offVals);
count('EXP_OFFLINE_N', offN);

fs.writeFileSync(path.join(__dirname, 'parity_expected.h'), out.join('\n') + '\n');
console.log('parity_expected.h written — ' +
            (tapVals.length + phaseSums.length + kw.length + gc.length + tf.length +
             rend.length + latv.length + offVals.length) + ' expected values');
